### ISSUE TITLE
Hi, I have encountered some questions and I also have some details to confirm with you.

### ISSUE THREAD

**Issue by young169** [cuihaoleo/kaggle-dfdc#1]
When I try to make dataset in the first step, there is an error occured:
'
Traceback (most recent call last):
  File "make_dataset.py", line 1, in <module>
    from face_utils import FaceDetector, norm_crop
  File "/mnt/mnt/users/lanyuyang/rk4kaggle-dfdc-master/face_utils.py", line 7, in <module>
    from data import cfg_re50
ModuleNotFoundError: No module named 'data'
'
And I don't know where the data folder or file comes from. Then I put the retina-face repo and efficientnet-pytorch repo in the external folder, and downloaded some weights you required, but the error is still there. Can you please help me a bit? Thanks

**Comment by jayxio** [comment]
Hi, you can download data from 
![image](https://user-images.githubusercontent.com/13096661/81542097-b5aba280-93a6-11ea-89d4-23c681a43af4.png) these file within on kaggle website `https://www.kaggle.com/cuihaoleo/dfdc-private-lb-4th-place-submission/comments#data `

Then, you should have error like something missing utils. You can download it from:
`https://github.com/biubug6/Pytorch_Retinaface/tree/master/utils`

Hope this will help.

**Comment by cuihaoleo** [comment]
Ideally, you should initialize code dependencies with `git submodule init` and `git submodule update` as said in README.

`RetinaFace-Resnet50-fixed.pth` is the pretrained RetinaFace weight file. Put it at the current working directory.

If you run `make_dataset.sh`, `PYTHONPATH` environment variable is set in the script to make python find RetinaFace. But if you want to run `make_dataset.py` directly, you should set `PYTHONPATH` yourself.

**Comment by young169** [comment]
Sorry to bother you further, Which files should I modify if I want to add some new data to train further? I find some possible required changings: 1. 'dfdc-data.csv' and 2.'dfdc.json'. And in 3. 'wsdan-conf/xception.py' the datapath is the image path generated by make_dataset.sh? Is there something I missed? The training procedure failed and I guess it's for path reasons

**Comment by cuihaoleo** [comment]
For Xception training:
- Use `dfdc-data.csv` to list all video files and specify which set a video belongs to.
- Set `data_root` in `xception_conf.py` as the root path of extracted video frames.

For WS-DAN:
- Use `dfdc.json` to list all video files.
- Set `datapath` in `wsdan-conf/xception.py` (or `wsdan-conf/efb3.py` for the efficientnet variant) as the root path of extracted video frames.

The inconsistency is because our members has been working in parallel at the early stage of the competition and implemented different dataset loaders.

We didn't take time to unify the code. Instead, we just left the messy code as-is. If you want to re-use the code, I would suggest you to replace the dataset loader with a unified one.

**Comment by young169** [comment]
Thanks, but after generating the json file and csv, and train wsdan-xception, the backward seems to fail and throws the following error:
"RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8]] is at version 4; expected version 3 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!"
I searched for some solutions but it still didn't work.
